;This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.34"

; Modules
projects[addressfield][type] = module
projects[addressfield][version] = "1.0"
projects[addressfield][subdir] = "contrib"

projects[advanced_link][type] = module
projects[advanced_link][version] = "1.3"
projects[advanced_link][subdir] = "contrib"

projects[bean][type] = module
projects[bean][version] = "1.7"
projects[bean][subdir] = "contrib"

projects[breakpoints][type] = module
projects[breakpoints][version] = "1.1"
projects[breakpoints][subdir] = "contrib"

projects[checklistapi][type] = module
projects[checklistapi][version] = "1.2"
projects[checklistapi][subdir] = "contrib"

projects[seo_checklist][type] = module
projects[seo_checklist][version] = "4.1"
projects[seo_checklist][subdir] = "contrib"

projects[ckeditor][type] = module
projects[ckeditor][version] = "1.16"
projects[ckeditor][subdir] = contrib

projects[ctools][type] = module
projects[ctools][version] = "1.7"
projects[ctools][subdir] = "contrib"

projects[coder][type] = module
projects[coder][version] = "2.2"
projects[coder][subdir] = "contrib"

projects[commerce][type] = module
projects[commerce][version] = "1.11"
projects[commerce][subdir] = "contrib"

projects[commerce_cart_expiration][type] = module
projects[commerce_cart_expiration][version] = "1.1"
projects[commerce_cart_expiration][subdir] = "contrib"

projects[commerce_stock][type] = module
projects[commerce_stock][version] = "2.0"
projects[commerce_stock][subdir] = "contrib"

projects[contact_google_analytics][type] = module
projects[contact_google_analytics][version] = "1.4"
projects[contact_google_analytics][subdir] = "contrib"

projects[date][type] = module
projects[date][version] = "2.8"
projects[date][subdir] = "contrib"

projects[entity][type] = module
projects[entity][version] = "1.6"
projects[entity][subdir] = "contrib"

projects[entityreference][type] = module
projects[entityreference][version] = "1.1"
projects[entityreference][subdir] = "contrib"

projects[entity_translation][type] = module
projects[entity_translation][version] = "1.0-beta3"
projects[entity_translation][subdir] = "contrib"

projects[epsacrop][type] = module
projects[epsacrop][version] = "2.x-dev"
projects[epsacrop][subdir] = "contrib"

projects[features][type] = module
projects[features][version] = "2.0"
projects[features][subdir] = "contrib"

projects[field_collection][type] = module
projects[field_collection][version] = "1.0-beta7"
projects[field_collection][subdir] = "contrib"

projects[field_display_label][type] = module
projects[field_display_label][version] = "1.3"
projects[field_display_label][subdir] = "contrib"

projects[field_group][type] = module
projects[field_group][version] = "1.4"
projects[field_group][subdir] = "contrib"

; We need dev snapshot for ctools export functionality.
projects[galleria][type] = module
projects[galleria][version] = "1.x-dev"
projects[galleria][subdir] = "contrib"

projects[ga_tokenizer][type] = module
projects[ga_tokenizer][version] = "1.5"
projects[ga_tokenizer][subdir] = "contrib"

projects[geofield][type] = module
projects[geofield][version] = "2.1"
projects[geofield][subdir] = "contrib"

projects[geophp][type] = module
projects[geophp][version] = "1.7"
projects[geophp][subdir] = "contrib"

projects[getdirections][type] = module
projects[getdirections][version] = "3.x-dev"
projects[getdirections][subdir] = "contrib"

projects[globalredirect][type] = module
projects[globalredirect][version] = "1.5"
projects[globalredirect][subdir] = "contrib"

projects[google_analytics][type] = module
projects[google_analytics][version] = "2.1"
projects[google_analytics][subdir] = "contrib"

projects[htmlpurifier][type] = module
projects[htmlpurifier][version] = "1.0"
projects[htmlpurifier][subdir] = "contrib"

projects[i18n][type] = module
projects[i18n][version] = "1.11"
projects[i18n][subdir] = "contrib"

projects[jquery_update][type] = module
projects[jquery_update][version] = "2.4"
projects[jquery_update][subdir] = "contrib"

projects[leaflet][type] = module
projects[leaflet][version] = "1.1"
projects[leaflet][subdir] = "contrib"
; Export all leaflet views style settings.
projects[leaflet][patch][] = "https://www.drupal.org/files/issues/export_all_leaflet_views_style_settings-2245717-0.patch"

projects[leaflet_more_maps][type] = module
projects[leaflet_more_maps][version] = "1.9"
projects[leaflet_more_maps][subdir] = "contrib"

projects[libraries][type] = module
projects[libraries][version] = "2.2"
projects[libraries][subdir] = "contrib"

projects[link][type] = module
projects[link][version] = "1.2"
projects[link][subdir] = "contrib"

projects[migrate][type] = module
projects[migrate][version] = "2.5"
projects[migrate][subdir] = "contrib"

projects[metatag][type] = module
projects[metatag][version] = "1.1"
projects[metatag][subdir] = "contrib"

projects[microdata][type] = module
projects[microdata][version] = "1.0-beta2"
projects[microdata][subdir] = "contrib"

projects[module_filter][type] = module
projects[module_filter][version] = "2.0-alpha2"
projects[module_filter][subdir] = "contrib"

projects[navbar][type] = module
projects[navbar][version] = "1.4"
projects[navbar][subdir] = "contrib"

projects[panels][type] = module
projects[panels][version] = "3.4"
projects[panels][subdir] = "contrib"

projects[panels_everywhere][type] = module
projects[panels_everywhere][version] = "1.0-rc1"
projects[panels_everywhere][subdir] = "contrib"

projects[pathauto][type] = module
projects[pathauto][version] = "1.2"
projects[pathauto][subdir] = "contrib"

projects[redirect][type] = module
projects[redirect][version] = "1.0-rc1"
projects[redirect][subdir] = "contrib"

projects[rooms][type] = module
projects[rooms][download][type] = "git"
projects[rooms][download][url] = "git@github.com:BluesparkLabs/DrupalRoomsModule.git"
projects[rooms][directory_name] = "rooms"
projects[rooms][subdir] = "contrib"

projects[rooms_availability_constraints][type] = module
projects[rooms_availability_constraints][download][type] = "git"
projects[rooms_availability_constraints][download][url] = "git@github.com:BluesparkLabs/rooms_availability_constraints.git"
projects[rooms_availability_constraints][directory_name] = "rooms_availability_constraints"
projects[rooms_availability_constraints][download][tag] = "RoomsAvailabilityConstraints-Casa-1.0.4"
projects[rooms_availability_constraints][subdir] = "contrib"

projects[rooms_package][type] = module
projects[rooms_package][download][type] = "git"
projects[rooms_package][download][url] = "git@github.com:BluesparkLabs/rooms_package.git"
projects[rooms_package][directory_name] = "rooms_package"
projects[rooms_package][subdir] = "contrib"

projects[rules][type] = module
projects[rules][version] = "2.7"
projects[rules][subdir] = "contrib"

projects[search404][type] = module
projects[search404][version] = "1.3"
projects[search404][subdir] = "contrib"

projects[seo_checker][type] = module
projects[seo_checker][version] = "1.7"
projects[seo_checker][subdir] = "contrib"

projects[site_verify][type] = module
projects[site_verify][version] = "1.1"
projects[site_verify][subdir] = "contrib"

projects[strongarm][type] = module
projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = "contrib"

projects[switchtheme][type] = module
projects[switchtheme][version] = "1.x-dev"
projects[switchtheme][subdir] = "contrib"
; Disable certain themes from theme switcher.
projects[switchtheme][patch][] = "https://www.drupal.org/files/1159884.8-switchtheme-disable-option.patch"
projects[switchtheme][patch][] = "https://www.drupal.org/files/issues/switchtheme-autosubmit-on-select-2304331.patch"

projects[title][type] = module
projects[title][version] = "1.0-alpha7"
projects[title][subdir] = "contrib"

projects[token][type] = module
projects[token][version] = "1.5"
projects[token][subdir] = "contrib"

projects[variable][type] = module
projects[variable][version] = "2.5"
projects[variable][subdir] = "contrib"

projects[views][type] = module
projects[views][version] = "3.10"
projects[views][subdir] = "contrib"

projects[views_slideshow][type] = module
projects[views_slideshow][version] = "3.1"
projects[views_slideshow][subdir] = "contrib"

projects[views_slideshow_galleria][type] = module
projects[views_slideshow_galleria][version] = "3.2"
projects[views_slideshow_galleria][subdir] = "contrib"

projects[vvf][type] = module
projects[vvf][version] = "1.1"
projects[vvf][subdir] = "contrib"

projects[xmlsitemap][type] = module
projects[xmlsitemap][version] = "2.0"
projects[xmlsitemap][subdir] = "contrib"

projects[site_map][type] = module
projects[site_map][version] = "1.2"
projects[site_map][subdir] = "contrib"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][type] = get
libraries[ckeditor][download][url] = http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.0.1/ckeditor_4.0.1_standard.zip
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[moment][download][type] = "file"
libraries[moment][download][url] = "http://momentjs.com/downloads/moment.min.js"
libraries[moment][directory_name] = "moment"
libraries[moment][type] = "library"

libraries[galleria][download][type] = "file"
libraries[galleria][download][url] = "http://galleria.io/static/galleria-1.3.5.zip"
libraries[galleria][directory_name] = "galleria"
libraries[galleria][type] = "library"

libraries[Jcrop][download][type] = "file"
libraries[Jcrop][download][url] = "http://github.com/tapmodo/Jcrop/archive/v0.9.12.zip"
libraries[Jcrop][directory_name] = "jcrop"
libraries[Jcrop][type] = "library"
libraries[Jcrop][overwrite] = TRUE
libraries[Jcrop][destination] = "modules/contrib/epsacrop"

libraries[json2][download][type] = "file"
libraries[json2][download][url] = "http://github.com/douglascrockford/JSON-js/archive/master.zip"
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"
libraries[json2][overwrite] = TRUE
libraries[json2][destination] = "modules/contrib/epsacrop"

libraries[showroom][download][type] = "file"
libraries[showroom][download][url] = "http://github.com/bluesparklabs/showroom/archive/master.zip"
libraries[showroom][directory_name] = "galleria/themes/showroom"
libraries[showroom][type] = "library"

libraries[leaflet][download][type] = "file"
libraries[leaflet][download][url] = "http://leaflet-cdn.s3.amazonaws.com/build/leaflet-0.6.4.zip"
libraries[leaflet][directory_name] = "leaflet"
libraries[leaflet][type] = "library"

libraries[backbone][download][type] = "file"
libraries[backbone][download][url] = "https://github.com/documentcloud/backbone/archive/1.0.0.zip"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

libraries[underscore][download][type] = "file"
libraries[underscore][download][url] = "https://github.com/documentcloud/underscore/archive/1.6.0.zip"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

libraries[modernizr][download][type] = "file"
libraries[modernizr][download][url] = "https://github.com/Modernizr/Modernizr/archive/v2.7.1.zip"
libreries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

libraries[htmlpurifier][download][type] = "file"
libraries[htmlpurifier][download][url] = "http://htmlpurifier.org/releases/htmlpurifier-4.6.0.zip"
libraries[htmlpurifier][directory_name] = "htmlpurifier"
libraries[htmlpurifier][type] = "library"

