<?php
$plugin = array(
  'title'     => t('Default Site Template'),
  'theme'     => 'l-page-default',
  'icon'      => 'l-page-default.png',
  'admin css' => '../../css/stanza.layouts.css',
  'category'  => 'Site Templates',
  'regions' => array(
    'branding'          => t('Branding'),
    'main'              => t('Main content'),
    'footer'            => t('Footer'),
    'help'              => t('Help'),
    'hero'              => t('Hero'),
    'leader'            => t('Leader'),
    'nav'               => t('Navigation'),
    'utility'           => t('Utility'),
  ),
);
