<?php
$plugin = array(
  'title'     => t('Casa Stacked'),
  'theme'     => 'casa-stacked',
  'icon'      => 'preview.png',
  'admin css' => '../../css/layouts/layout.casa-stacked.css',
  'category'  => 'Casa',
  'regions' => array(
    'highlighted'       => t('Highlighted'),
    'main'              => t('Main content'),
    'main_left'         => t('Main left'),
    'main_right'        => t('Main right'),
    'secondary_left'    => t('Secondary left'),
    'secondary_right'   => t('Secondary right'),
    'secondary_middle'  => t('Secondary middle'),
    'tertiary'          => t('Tertiary'),
  ),
);
